title: "My Jekyll Site"
description: "A simple site using Jekyll and the Minimal theme."
theme: jekyll-theme-minimal
url: "https://nkapoor11.github.io"
logo: headshot.jpg
social: 
  email: "neilkapoor11@gmail.com"
  linkedin: "https://www.linkedin.com/in/neil-kapoor/"
