title: "My Jekyll Site"
description: "A simple site using Jekyll and the Minimal theme."
theme: minimal
url: "https://yourusername.github.io"
baseurl: "/repository-name"  # (if hosted in a subdirectory on GitHub Pages)
